openapi: '3.0.0'
info:
  title: Rails Scoffold
  description: this is a demo of rails scaffold api document
  version: 1.0.0
  contact:
    name: Gary
    # url: google.com.tw
    email: gary@example.com

servers:
- url: localhost:3000
  description: this is a local application
tags:
- name: home
  description: main scaffold
- name: test
  description: act like a postman
paths:
  /users:
    get:
      tags: 
      - home
      description: |
        get home page imformation
      responses:
          200:
            description: Get home page sucessfully
          400:
            description: Get home page fail
  /users:
    post:
  /users/new:
    get:
  /users/{id}/edit:
    get:
      tags: 
      - home
  /users/{id}:
    get:
      tags: 
      - home
  /users/{id}:
    put:
      tags: 
      - home
  /users/{id}:
    delete:
      tags: 
      - home
  /tests:
    get:
      tags: 
      - test
