openapi: '3.0.0'
info:
  title: Rails Scoffold
  description: this is a demo of rails scaffold api document
  version: 1.0.0
  contact:
    name: Gary
    # url: google.com.tw
    email: gary@example.com

servers:
- url: http://localhost:3000
  description: this is a local application
tags:
- name: home
  description: main scaffold
- name: test
  description: act like a postman
paths:
  /users:
    get:
      tags: 
      - home
      description: |
        get home page imformation
      responses:
          200:
            description: Get home page sucessfully
          400:
            description: Get home page fail
    post:
      tags: 
      - home
      responses:
          200:
            description: Get home page sucessfully
          400:
            description: Get home page fail
  /users/new:
    get:
      tags: 
      - home
      responses:
          200:
            description: Get home page sucessfully
          400:
            description: Get home page fail
  /users/{id}/edit:
    get:
      tags: 
      - home
      parameters:
      - $ref: "#/components/parameters/User"
      responses:
          200:
            description: Get home page sucessfully
          400:
            description: Get home page fail
  /users/{id}.json:
    get:
      tags: 
      - home
      parameters:
      - $ref: "#/components/parameters/User"
      responses:
          200:
            description: Get home page sucessfully
          400:
            description: Get home page fail
    put:
      tags: 
      - home
      parameters:
      - $ref: "#/components/parameters/User"
      responses:
          200:
            description: Get home page sucessfully
          400:
            description: Get home page fail
    delete:
      tags: 
      - home
      parameters:
      - $ref: "#/components/parameters/User"
      responses:
          200:
            description: Get home page sucessfully
          400:
            description: Get home page fail
  /tests:
    get:
      tags: 
      - test
      responses:
          200:
            description: Get home page sucessfully
          400:
            description: Get home page fail

components:
  parameters:
    User:
      name: id
      in: "path"
      description: Find out which user
      schema:
        type: integer
      required: true
      example: 1